#ifndef CONSTANTS_H
#define DEFAULT_CONSTANTS_H

#define DEFAULT_HOT_SHELF_MAX_SIZE                      10
#define DEFAULT_COLD_SHELF_MAX_SIZE                     10
#define DEFAULT_FROZEN_SHELF_MAX_SIZE                   10
#define DEFAULT_OVERFLOW_SHELF_MAX_SIZE                 15

#define DEFAULT_KITCHEN_INGESTION_INTERVAL              1000 
#define DEFAULT_KITCHEN_INGESTION_RATE                  2
#define DEFAULT_KITCHEN_COURIER_DISPATCH_INTERVAL_MIN   2000
#define DEFAULT_KITCHEN_COURIER_DISPATCH_INTERVAL_MAX   4000

#define DEFAULT_SHELF_MONITOR_INTERVAL                  1500
#define DEFAULT_SHELF_LIFE_MODIFIER_SINGLE_TEMP_SHELF   1
#define DEFAULT_SHELF_LIFE_MODIFIER_OVERFLOW_SHELF      2
#define DEFAULT_DEBUG_LEVEL                             (L4)
#define DEFAULT_SYSTEM_ORDERS_INPUT_FILE                "orders.json"
#define DEFAULT_SYSTEM_PRINT_SHELF_CONTENTS             true

int HOT_SHELF_MAX_SIZE;
int COLD_SHELF_MAX_SIZE;
int FROZEN_SHELF_MAX_SIZE;
int OVERFLOW_SHELF_MAX_SIZE;

int KITCHEN_INGESTION_INTERVAL;//msecs
int KITCHEN_INGESTION_RATE;//no. of records to process in each ingestion tick
int KITCHEN_COURIER_DISPATCH_INTERVAL_MIN; //msecs
int KITCHEN_COURIER_DISPATCH_INTERVAL_MAX; //msecs

int SHELF_MONITOR_INTERVAL;
int SHELF_LIFE_MODIFIER_SINGLE_TEMP_SHELF;
int SHELF_LIFE_MODIFIER_OVERFLOW_SHELF;

int SYSTEM_DEBUG_LEVEL; //L1 | L2 | L3 | L4 | NONE
char *SYSTEM_ORDERS_INPUT_FILE; //"orders.json"
bool SYSTEM_PRINT_SHELF_CONTENTS;

#endif //CONSTANTS_H